set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# Minimal tmux status theme
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-bg '#5f87af'
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status-right "#S [#h]"

# Vi-style splits and pane navigation
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Floating pane toggle
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind 'F'

# TPM (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
