set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# Minimal tmux status theme
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-bg '#5f87af'
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status-right "#S [#h]"

# TPM (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
