"""
""" Still need to import a bunch of customizations
""" https://github.com/nclark/dotfiles/blob/47cc9e3fea39f011be28782a32937f336b135f1f
"""
"
" temp
"

" General options
set showcmd
set ruler
set textwidth=100

" Leader
let mapleader=";"

" Syntax highlighting
syntax on
filetype plugin indent on

" Shut up the damn bells!
set noeb vb t_vb=

" add tags.gem to tagstack
set tags+=gems.tags

" add shortcut for Tagbar
nmap <Leader>t :TagbarToggle<CR>
imap <Leader>t <Esc>:TagbarToggle<CR>

" Keymap
imap jj <Esc>                           " jj to exit insert mode
nmap <Leader>f ggVG=<CR>                " format code
nmap <Leader>bt :!ctags-bundler<CR><CR> " generate ctags from Gemfile

"" window navigation
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l
imap <C-h> <Esc><C-W>h<CR>
imap <C-j> <Esc><C-W>j<CR>
imap <C-k> <Esc><C-W>k<CR>
imap <C-l> <Esc><C-W>l<CR>

" folding - http://www.linode.com/wiki/index.php/Vim_Tutorial
set foldenable
set foldmethod=indent
set foldlevel=100
set foldopen-=undo

" git diff
inoremap <leader>d <Esc>:Gvdiff<CR>
nnoremap <leader>d :Gvdiff<CR>

" Start pathogen
call pathogen#infect()

