#!/usr/bin/env ruby

require 'uri'

gh       = 'https://github.com'
origin   = `git config --get remote.origin.url`.chomp
uri      = URI.parse("https://#{origin.gsub(':', '/')}")
path     = uri.path.gsub('.git', '')
base     = "#{gh}#{path}"
branch   = `git rev-parse --abbrev-ref HEAD`.chomp

url = case ARGV.shift

when 'compare', 'cmp'
  "#{base}/compare/#{branch}?expand=1"
when 'index', 'list', 'ls'
  "#{base}/commits/#{branch}"
when 'show', 'diff', 'df'
  head_sha = `git rev-parse HEAD`.chomp

  "#{base}/commit/#{head_sha}"
when 'branch', 'br'
  "#{base}/tree/#{branch}"
when 'ci'
  "https://circleci.com/gh#{path}/tree/#{branch}"
when 'help'
  puts "git hub [command]\n"
  puts "\nCommands:"
  puts "  compare | cmp | "
  puts "  index   | ls  | list "
  puts "  show    | df  | diff "
  puts "  branch  | br  |"

  exit
else
  puts 'what?'

  exit
end

puts "Opening #{url}..."
system("open '#{url}'")

