#!/usr/bin/env ruby

require 'rubygems'
require 'httparty'

class TrackerStory
  include HTTParty
  base_uri "https://www.pivotaltracker.com/services/v3"

  def initialize(story_id)
    @story_id = story_id
    self.class.headers 'X-TrackerToken' => api_token
  end

  def result
    @result ||= fetch
  end

  def name
    result['story']['name'].downcase.gsub(/\s/, '_').gsub(/[^[:alnum:]_]/, '')
  end

  protected

  def fetch
    self.class.get("/projects/#{project_id}/stories/#{@story_id}")
  end

  def api_token
    `git config --get pivotal.api-token`.chomp
  end

  def project_id
    `git config --get pivotal.project-id`.chomp
  end
end


branch_name = TrackerStory.new(ARGV[0]).name
system("git co master")
system("git co -b #{branch_name}")

