#!/usr/bin/env ruby

require 'uri'

origin = `git config --get remote.origin.url`.chomp

if origin =~ /github/
  branch      = `git rev-parse --abbrev-ref HEAD`.chomp
  uri         = URI.parse("https://#{origin.gsub(':', '/')}")
  path        = uri.path.gsub('.git', '')
  compare_url = "https://github.com#{path}/compare/#{branch}?expand=1"

  puts compare_url
  system("open '#{compare_url}'")
end
