#!/usr/bin/env ruby

story_branches = `git br 2>&1`.split.select {|i| i =~ /^US/}

story_branches.each do |branch|
  description = `ralio show #{branch} 2>&1 | head -1`.chomp

  puts "#{branch}: #{description}"
end

