#!/usr/bin/env ruby

## please don't read this

require 'uri'

def whole_branch
  branch      = `git rev-parse --abbrev-ref HEAD`.chomp
  uri         = URI.parse("https://#{@origin.gsub(':', '/')}")
  path        = uri.path.gsub('.git', '')
  compare_url = "https://github.com#{path}/compare/#{branch}?expand=1"

  puts compare_url
  system("open '#{compare_url}'")
end

def certain_commits
  count  = ARGV[0].to_i + 1
  branch = `git rev-parse --abbrev-ref HEAD`.chomp
  uri    = URI.parse("https://#{@origin.gsub(':', '/')}")
  path   = uri.path.gsub('.git', '')

  first_commit_sha = `git log --pretty=format:'%h' | head -n #{count} | head -n 1`.chomp
  last_commit_sha = `git log --pretty=format:'%h' | head -n #{count} | tail -n 1`.chomp
  compare_url = "https://github.com#{path}/compare/#{last_commit_sha}...#{first_commit_sha}"

  puts compare_url
  system("open '#{compare_url}'")
end

@origin = `git config --get remote.origin.url`.chomp

unless @origin =~ /github/
  puts "Only github is supported"

  exit
end

if ARGV[0]
  certain_commits
else
  whole_branch
end

