#!/usr/bin/env ruby

require 'tempfile'

def yellow(text)
  "\e[33m#{text}\e[0m"
end

def green(text)
  "\e[32m#{text}\e[0m"
end

def bold(text)
  "\e[1m#{text}\e[22m"
end

def write_branches
  Tempfile.new.tap do |f|
    `git branch`.split.reject {|e| e == '*'}.each do |branch|
      f.write "#{branch}\n"
    end

    f.close
  end
end

def choose_branches(tempfile)
  system "vim #{tempfile.path}"

  tempfile.open
  tempfile.read.split
end

def archive_branches(branches)
  branches.each { |branch| puts branch }

  print "\nReady to proceed [y/N] > "

  if STDIN.gets.chomp == 'y'
    branches.each do |branch|

      puts yellow("Archiving...")
      system("git archive-branch #{branch}")
      puts yellow("done.")
    end
  end
end

tempfile = write_branches
branches = choose_branches(tempfile)
archive_branches(branches)
