## includes
source ~/.zsh/env
source ~/.zsh/compinstall

source ~/.zsh/aliases
source ~/.zsh/autocomplete
source ~/.zsh/functions

source ~/.zsh/misc/ec2

source ~/.zsh/private

## prompt
setopt prompt_subst

PS1='[%n]%15<...<%~%<<% $(git_prompt_info) # '

## history
bindkey '^R' history-incremental-search-backward

## colors
eval `gdircolors ~/.dir_colors`

## rvm
source $HOME/.rvm/scripts/rvm

eval "$(direnv hook zsh)"

## kiex
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
